### ISSUE TITLE
Black image in output

### ISSUE THREAD

**Issue by VVh5912** [irasin/Pytorch_MST#2]
Hi, I was trying to execute this python file in Colab.
I tried with the example of brad_pitt.jpg as the content and in2.jpg as the style. However, I got an black image in the output.
Can you help me up with the issue

**Comment by irasin** [comment]
This is a very old project, so changes in the python package may cause incorrect results, but I think it shouldn't be a big problem. I no longer maintain this project, please resolve it yourself. Thanks
